// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: sandbox.proto

package sandbox

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SanitizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayloadJson   string                 `protobuf:"bytes,1,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SanitizeRequest) Reset() {
	*x = SanitizeRequest{}
	mi := &file_sandbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SanitizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SanitizeRequest) ProtoMessage() {}

func (x *SanitizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SanitizeRequest.ProtoReflect.Descriptor instead.
func (*SanitizeRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{0}
}

func (x *SanitizeRequest) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type SanitizeResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SanitizedJson      string                 `protobuf:"bytes,1,opt,name=sanitized_json,json=sanitizedJson,proto3" json:"sanitized_json,omitempty"`
	Redacted           bool                   `protobuf:"varint,2,opt,name=redacted,proto3" json:"redacted,omitempty"`
	FieldsRedacted     uint32                 `protobuf:"varint,3,opt,name=fields_redacted,json=fieldsRedacted,proto3" json:"fields_redacted,omitempty"`
	IsSafe             bool                   `protobuf:"varint,4,opt,name=is_safe,json=isSafe,proto3" json:"is_safe,omitempty"`
	WafViolationReason string                 `protobuf:"bytes,5,opt,name=waf_violation_reason,json=wafViolationReason,proto3" json:"waf_violation_reason,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SanitizeResponse) Reset() {
	*x = SanitizeResponse{}
	mi := &file_sandbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SanitizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SanitizeResponse) ProtoMessage() {}

func (x *SanitizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SanitizeResponse.ProtoReflect.Descriptor instead.
func (*SanitizeResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_proto_rawDescGZIP(), []int{1}
}

func (x *SanitizeResponse) GetSanitizedJson() string {
	if x != nil {
		return x.SanitizedJson
	}
	return ""
}

func (x *SanitizeResponse) GetRedacted() bool {
	if x != nil {
		return x.Redacted
	}
	return false
}

func (x *SanitizeResponse) GetFieldsRedacted() uint32 {
	if x != nil {
		return x.FieldsRedacted
	}
	return 0
}

func (x *SanitizeResponse) GetIsSafe() bool {
	if x != nil {
		return x.IsSafe
	}
	return false
}

func (x *SanitizeResponse) GetWafViolationReason() string {
	if x != nil {
		return x.WafViolationReason
	}
	return ""
}

var File_sandbox_proto protoreflect.FileDescriptor

const file_sandbox_proto_rawDesc = "" +
	"\n" +
	"\rsandbox.proto\x12\asandbox\"4\n" +
	"\x0fSanitizeRequest\x12!\n" +
	"\fpayload_json\x18\x01 \x01(\tR\vpayloadJson\"\xc9\x01\n" +
	"\x10SanitizeResponse\x12%\n" +
	"\x0esanitized_json\x18\x01 \x01(\tR\rsanitizedJson\x12\x1a\n" +
	"\bredacted\x18\x02 \x01(\bR\bredacted\x12'\n" +
	"\x0ffields_redacted\x18\x03 \x01(\rR\x0efieldsRedacted\x12\x17\n" +
	"\ais_safe\x18\x04 \x01(\bR\x06isSafe\x120\n" +
	"\x14waf_violation_reason\x18\x05 \x01(\tR\x12wafViolationReason2X\n" +
	"\x0eSandboxService\x12F\n" +
	"\x0fSanitizePayload\x12\x18.sandbox.SanitizeRequest\x1a\x19.sandbox.SanitizeResponseBUZSgithub.com/amitav400c/ondc-analytics-gateway/gateway-ingress/internal/proto/sandboxb\x06proto3"

var (
	file_sandbox_proto_rawDescOnce sync.Once
	file_sandbox_proto_rawDescData []byte
)

func file_sandbox_proto_rawDescGZIP() []byte {
	file_sandbox_proto_rawDescOnce.Do(func() {
		file_sandbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandbox_proto_rawDesc), len(file_sandbox_proto_rawDesc)))
	})
	return file_sandbox_proto_rawDescData
}

var file_sandbox_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sandbox_proto_goTypes = []any{
	(*SanitizeRequest)(nil),  // 0: sandbox.SanitizeRequest
	(*SanitizeResponse)(nil), // 1: sandbox.SanitizeResponse
}
var file_sandbox_proto_depIdxs = []int32{
	0, // 0: sandbox.SandboxService.SanitizePayload:input_type -> sandbox.SanitizeRequest
	1, // 1: sandbox.SandboxService.SanitizePayload:output_type -> sandbox.SanitizeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sandbox_proto_init() }
func file_sandbox_proto_init() {
	if File_sandbox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandbox_proto_rawDesc), len(file_sandbox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sandbox_proto_goTypes,
		DependencyIndexes: file_sandbox_proto_depIdxs,
		MessageInfos:      file_sandbox_proto_msgTypes,
	}.Build()
	File_sandbox_proto = out.File
	file_sandbox_proto_goTypes = nil
	file_sandbox_proto_depIdxs = nil
}
